#!/bin/sh

PREFIX=../../src
FIOTRACE=~/Desktop/FIO_trace
RESULT=~/Desktop/FIO_trace/result


${PREFIX}/disksim hybrid-maxtor-optimal10.parv ${RESULT}/5_write_seq_3g_256iodep.outv ascii ${FIOTRACE}/write_seq_3g_256iodep.trace 0 ssd0x0 "Reserve pages percentage" 50

${PREFIX}/disksim hybrid-maxtor-optimal10.parv ${RESULT}/5_rw50_seq25_3g_256iodep.outv ascii ${FIOTRACE}/rw50_seq25_3g_256iodep.trace 0 ssd0x0 "Reserve pages percentage" 50
${PREFIX}/disksim hybrid-maxtor-optimal10.parv ${RESULT}/5_rw50_seq50_3g_256iodep.outv ascii ${FIOTRACE}/rw50_seq50_3g_256iodep.trace 0 ssd0x0 "Reserve pages percentage" 50
${PREFIX}/disksim hybrid-maxtor-optimal10.parv ${RESULT}/5_rw50_seq75_3g_256iodep.outv ascii ${FIOTRACE}/rw50_seq75_3g_256iodep.trace 0 ssd0x0 "Reserve pages percentage" 50

